window.esdocSearchIndex = [
  [
    "hoist-connector-wordpress/src/connector.js~wordpressconnector",
    "class/src/connector.js~WordpressConnector.html",
    "<span>WordpressConnector</span> <span class=\"search-result-import-path\">hoist-connector-wordpress/src/connector.js</span>",
    "class"
  ],
  [
    "hoist-connector-wordpress/src/poll.js~poll",
    "function/index.html#static-function-poll",
    "<span>poll</span> <span class=\"search-result-import-path\">hoist-connector-wordpress/src/poll.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/tests/integration_tests/auth_tests.js.html#lineNumber10",
    "authorization steps",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/auth_tests.js.html#lineNumber29",
    "authorization steps on first bounce",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/auth_tests.js.html#lineNumber61",
    "authorization steps on first bounce should receive a redirect",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/auth_tests.js.html#lineNumber58",
    "authorization steps on first bounce should save current step",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/auth_tests.js.html#lineNumber65",
    "authorization steps on return from Wordpress",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/auth_tests.js.html#lineNumber125",
    "authorization steps on return from Wordpress should save state",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/settings_tests.js.html#lineNumber6",
    "default settings",
    "test"
  ],
  [
    "",
    "test-file/tests/unit_tests/settings_tests.js.html#lineNumber8",
    "default settings exposes defaultSettings method",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/batch_tests.js.html#lineNumber7",
    "get posts and comments",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/batch_tests.js.html#lineNumber45",
    "get posts and comments can extract latest comment",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/batch_tests.js.html#lineNumber42",
    "get posts and comments returns correct response",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/sites_tests.js.html#lineNumber7",
    "get sites",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/sites_tests.js.html#lineNumber48",
    "get sites returns users projects",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/posts_tests.js.html#lineNumber4",
    "posts api",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/posts_tests.js.html#lineNumber6",
    "posts api create new post",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/posts_tests.js.html#lineNumber48",
    "posts api create new post returns correct response",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/posts_tests.js.html#lineNumber137",
    "posts api delete post",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/posts_tests.js.html#lineNumber178",
    "posts api delete post returns correct response",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/posts_tests.js.html#lineNumber91",
    "posts api edit post",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/posts_tests.js.html#lineNumber133",
    "posts api edit post returns correct response",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/posts_tests.js.html#lineNumber52",
    "posts api get posts",
    "test"
  ],
  [
    "",
    "test-file/tests/integration_tests/posts_tests.js.html#lineNumber87",
    "posts api get posts returns correct response",
    "test"
  ],
  [
    "src/connector.js",
    "file/src/connector.js.html",
    "src/connector.js",
    "file"
  ],
  [
    "src/connector.js~oauth2connectorbase",
    "external/index.html",
    "src/connector.js~OAuth2ConnectorBase",
    "external"
  ],
  [
    "src/connector.js~wordpressconnector#constructor",
    "class/src/connector.js~WordpressConnector.html#instance-constructor-constructor",
    "src/connector.js~WordpressConnector#constructor",
    "method"
  ],
  [
    "src/connector.js~wordpressconnector#delete",
    "class/src/connector.js~WordpressConnector.html#instance-method-delete",
    "src/connector.js~WordpressConnector#delete",
    "method"
  ],
  [
    "src/connector.js~wordpressconnector#get",
    "class/src/connector.js~WordpressConnector.html#instance-method-get",
    "src/connector.js~WordpressConnector#get",
    "method"
  ],
  [
    "src/connector.js~wordpressconnector#patch",
    "class/src/connector.js~WordpressConnector.html#instance-method-patch",
    "src/connector.js~WordpressConnector#patch",
    "method"
  ],
  [
    "src/connector.js~wordpressconnector#post",
    "class/src/connector.js~WordpressConnector.html#instance-method-post",
    "src/connector.js~WordpressConnector#post",
    "method"
  ],
  [
    "src/connector.js~wordpressconnector#put",
    "class/src/connector.js~WordpressConnector.html#instance-method-put",
    "src/connector.js~WordpressConnector#put",
    "method"
  ],
  [
    "src/connector.js~wordpressconnector.defaultsettings",
    "class/src/connector.js~WordpressConnector.html#static-method-defaultSettings",
    "src/connector.js~WordpressConnector.defaultSettings",
    "method"
  ],
  [
    "src/poll.js",
    "file/src/poll.js.html",
    "src/poll.js",
    "file"
  ],
  [
    "tests/integration_tests/auth_tests.js",
    "test-file/tests/integration_tests/auth_tests.js.html",
    "tests/integration_tests/auth_tests.js",
    "testFile"
  ],
  [
    "tests/integration_tests/batch_tests.js",
    "test-file/tests/integration_tests/batch_tests.js.html",
    "tests/integration_tests/batch_tests.js",
    "testFile"
  ],
  [
    "tests/integration_tests/posts_tests.js",
    "test-file/tests/integration_tests/posts_tests.js.html",
    "tests/integration_tests/posts_tests.js",
    "testFile"
  ],
  [
    "tests/integration_tests/sites_tests.js",
    "test-file/tests/integration_tests/sites_tests.js.html",
    "tests/integration_tests/sites_tests.js",
    "testFile"
  ],
  [
    "tests/unit_tests/settings_tests.js",
    "test-file/tests/unit_tests/settings_tests.js.html",
    "tests/unit_tests/settings_tests.js",
    "testFile"
  ]
]